APP_NAME = Haley
APP_DEBUG = true
APP_TIMEZONE = America/Sao_Paulo

DB_CONNECTION = mysql
DB_HOST = localhost
DB_PORT = 3306
DB_DATABASE = framework
DB_USERNAME = haley
DB_PASSWORD = root

MAILER_NAME = example
MAILER_RESPONSE = example@hotmal.com
MAILER_HOST =
MAILER_PORT =
MAILER_USERNAME =
MAILER_PASSWORD =

SERVER_HOST = localhost